# ------------------------------------------------------------------------------
# Test
# ------------------------------------------------------------------------------
FROM golang:latest AS test
LABEL NAME golang
LABEL VERSION 2.0
ENV APP /src/gotrader
WORKDIR ${APP}/src/gotrader
RUN mkdir -p ${APP}/src/gotrader
COPY . ${APP}/src/gotrader
COPY configs/config*.yml /opt/
RUN cd ${APP}/src/gotrader \
    && go test ./... -args config /opt/config-test.yml 
