version: '3.4'

services:
  redis:
    container_name: redis
    image: redis
    command: redis-server
    ports:
    - "6379:6379"
  builder:
    container_name: gotrader-builder
    build:
      context: .
      target: builder
  runner:
    environment:
      - ENV=prod
    container_name: gotrader
    build:
      context: .
      target: runner
    depends_on:
    - redis
    links:
    - redis
    environment:
    - REDIS_URL=redis://redis
