# User id to use API (required)
userid: ""

# Password/Secret key to use API (required)
secret: ""

# API endpoint/url. Aways use HTTPS! (required)
endpoint: "https://www.bitmex.com"

# Amount of contracts for trade. Only integers (required)
hand: 50

# Asset to trade (required)
asset: "XBTUSD"

# Cadle time (minutes). The minimum is 1 (required)
candle: 5

# threshold to trigger the rule (required)
threshold: 5

# Leverage value. Set a number between 0.01 and 100. 
# Send 0 to enable cross margin. (required) 
leverage: "10"

# Profit value to close (percentage)
profit: 0.1

# Stop Loss trigger (percentage)
stoploss: 6.0
