# User id to use API (bitmex example)
userid: "LAqUlngMIQkIUjXMUreyu3qn"

# Password to use API (bitmex example)
secret: "chNOOS4KvNXR_Xq4k4c9qsfoKWvnDecLATCRlcBwyKDYnWgO"

# API endpoint/url. Aways use HTTPS!
endpoint: "https://testnet.bitmex.com"

# Amount of contracts for trade. Only integers (required)
hand: 2

# Asset to trade
asset: "XBTUSD"

# Cadle time (minutes)
candle: 1

# threshold to trigger the rule.
threshold: 1

# Leverage value. Set a number between 0.01 and 100. 
# Send 0 to enable cross margin.
leverage: "0.1"

# Profit value to close (percentage)
profit: 0.1

# Stop Loss trigger (percentage)
stoploss: 1.0

# Enable matrix? (true/false)
matrixuse: false

# Matrix API KEY
matrix_key: "!xxxxxxx:matrix.org"

# Matrix API URL
matrixurl: "https://matrix.org"

# Matrix channel
matrixchannel: "@"

# TAAPI key
taapikey: "42"
